[package]
name = "mfxvnc"
version = "0.1.0"
authors = ["Yasuhiro Fujii <y-fujii@mimosa-pudica.net>"]

[dependencies]
byteorder = "*"
scrap = "*"
flate2 = "*"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
